### ISSUE TITLE
pip attempts to run setup.py on win32 system.

### ISSUE THREAD

**Issue by willtheorangeguy** [barry-scott/PythonWinAppPackager#1]
When I try to install the module the command prompt fails due to a problem with the version.txt file. Can this be fixed?

**Comment by barry-scott** [comment]
> On 19 Apr 2016, at 01:40, William notifications@github.com wrote:
> 
> When I try to install the module the command prompt fails due to a problem with the version.txt file. Can this be fixed?
> 
> Care to share details to help me understand what is wrong?
> Versions of windows and python. How you installed the code.
> And last but not lease the error you see.

Barry

**Comment by barry-scott** [comment]
Without context Ihave no idea if this is user error or bug.
I'm assuming user error. PLease reopen with details if I'm wrong.

**Comment by willtheorangeguy** [comment]
I installed it using the instructions in the Python documentation.

**Comment by barry-scott** [comment]
What python documentation?
1. Show the exact command line you use.
2. Show the output that the command gets you.

**Comment by willtheorangeguy** [comment]
This is what appears:
![delete](https://cloud.githubusercontent.com/assets/18339050/14838878/9c5de304-0bda-11e6-88aa-28fb5a0a85d4.PNG)
After using the installation method provided by the installation instructions on this page.

**Comment by barry-scott** [comment]
I get this with Windows 10 and python 3.5 win64.

: 13:45:24.60 C:\Users\barry\Desktop
: \BLACKSTAR\barry> py -3.5 -m pip install win-app-packager
Collecting win-app-packager
  Using cached win_app_packager-1.0.0-cp35-none-win_amd64.whl
Collecting namedstruct>=1.1 (from win-app-packager)
  Downloading namedstruct-1.1.0-py3-none-any.whl
Installing collected packages: namedstruct, win-app-packager
Successfully installed namedstruct-1.1.0 win-app-packager-1.0.0

Are you using win32 python 3.5? I wonder is PIP is attempting to compile the code for you.

**Comment by barry-scott** [comment]
I get thisattempting to install win32 version:

: 13:55:15.93 C:\Users\barry\Desktop
: \BLACKSTAR\barry> c:\Python35.win32\python -m pip install win-app-installer
Collecting win-app-installer
  Could not find a version that satisfies the requirement win-app-installer (from versions: )
No matching distribution found for win-app-installer

**Comment by willtheorangeguy** [comment]
I will try to install it one more time to see what I get.

**Comment by willtheorangeguy** [comment]
This is what I get when installing using Windows 10 32 bit and Python 3.5.1 using instructions from the front CODE page here on GitHub:
![del](https://cloud.githubusercontent.com/assets/18339050/15095580/9685c45a-1482-11e6-827f-854cfc8a961f.PNG)

**Comment by barry-scott** [comment]
My knowledge of pip is limited - I do not know why it is doing this.

What is happening is that pip has decided to compile the code rather then use the files in the wheel.
The wheel does not contain all the files needed to compile this package. Version.txt in only the start of the problems.

I cannot access PyPI at the moment to check on the package properties. But in the mean time
we may find out more if you install using the following command an see if there is any thing in the output that hints at why pip is going wrong.

Oh and please learn to cut-n-paste the text from CMD so you can stop posting images.
Check out the CMD properties and turn on the stuff that allows you to cut-n-paste.
(I'm on linux at the moment and cannot give more details).

The command to try is "py -3.5 -m pip -v -v -v install win-app-packager"

**Comment by barry-scott** [comment]
O.K. PyPi responding again. I think I can guess what is going on.
I only provided win64 build of the package.

I'll see what I need to do to create a win32.

I'm surprised you have a Windows 10 capable machine and run 32 bit windows on it.

**Comment by barry-scott** [comment]
The reason this does not work is that I have not provide win32 binaries.

And the reason for that is in the READMe.md - I have not had time to test and debug win32.

I have taken a quick look and it will take some code changes to deal with the system folder name changes.

**Comment by barry-scott** [comment]
I have now added win32 support and released 1.1.0 on win-app-packager for win32 and win64.

You should be able to install on windows 32 bit now.

**Comment by willtheorangeguy** [comment]
Thank You. Hopefully this solves the problem.
